routes:
    home: 'Default:home'
    articleview: 'Default:articleView'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    edit: 'User:edit'
    article: 'User:article'

defaut_route: 'home'

db_config:
    name: 'sup-wow'
    host: 'localhost'
    user: 'root'
    pass: 'root'

services:
    twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }
