routes:
    home: 'Default:home'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    profil: 'User:profil'
    article: 'User:article'

defaut_route: 'home'

db_config:
    name: 'sup-wow'
    host: 'localhost'
    user: 'root'
    pass: 'root'
