routes:
    home: 'Default:home'
    profilview: 'Default:profilView'
    articleview: 'Default:articleView'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    edit: 'User:edit'
    article: 'User:article'
    profil: 'User:profil'

defaut_route: 'home'

db_config:
    name: 'sup-wow'
    host: 'localhost'
    user: 'root'
    pass: 'root'